name: Add release from issue
on:
  issues:
    types: [opened]
jobs:
  add-release:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Json in Issue
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_json_payload
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_id: ${{ github.event.issue.number }}

      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "Successfully parsed issue body. Attempting to add release to package DB."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Checkout db branch
        uses: actions/checkout@master
        with: 
          ref: db

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Update package list
        id: update-package-list
        run: |
          poetry install
          RESULT=$(poetry run python3 src/c2modregistry/main.py add '${{ fromJson(steps.issue_json_payload.outputs.payload).repo_url }}' '${{ fromJson(steps.issue_json_payload.outputs.payload).release_tag }}')
          echo "::set-output name=result::$RESULT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Results
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: |
            ```
            ${{ steps.update-package-list.outputs.result }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package list
          branch: db
          file_pattern: package_db
