name: Add release from issue
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Add PR to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Chiv2-Community/projects/4
          github-token: ${{ secrets.PROJECT_MANAGER_PAT }}
          

  check-should-execute:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if this should execute
        id: check
        run: |
          shopt -s nocasematch
          SHOULD_EXECUTE=true

          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" != "retry" ]]; then
              echo "should_execute=false" >> $GITHUB_OUTPUT
            fi
          fi

          echo "should_execute=$SHOULD_EXECUTE" >> $GITHUB_OUTPUT
          
  parse-json:
    runs-on: ubuntu-latest
    needs: check-should-execute
    if: needs.check-should-execute.outputs.should_execute == 'true'
    outputs:
      json_payload: ${{ steps.issue_json_payload.outputs.payload }}
      failed: ${{ steps.issue_json_payload.outputs.failed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Parse Json in Issue
        id: issue_json_payload
        run:
          ./.github/workflows/scripts/extract-issue-json-body.sh "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post failure Results 
        uses: peter-evans/create-or-update-comment@v3
        if: steps.issue_json_payload.outputs.failed == 'true'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Failed to parse the json in the issue body. Copy and paste the template below and add it to
            the issue description. Fill out the fields with the correct details. When complete, respond 
            to this issue thread with "retry"
            ````
            ```
            {
              "repo_url": "https://github.com/Username/ExampleMod",
              "release_tag": "v0.0.1"
            }
            ```
            ````
            Check out the [Unchained Discord](https://discord.gg/chiv2unchained) for support.
             
  add-release:
    runs-on: ubuntu-latest
    needs: parse-json
    if: needs.parse-json.outputs.failed == 'false'
    permissions:
      contents: write  # Needed for making changes to repo
      issues: write    # Needed for commenting on issues
    steps:
      - name: Confirmation Message
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Successfully parsed issue body. Attempting to add release to package DB."

      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Add release
        id: add-release
        uses: Chiv2-Community/zero-infra-mod-registry@main
        continue-on-error: true
        with:
          command: add
          repo_url: ${{ fromJson(needs.parse-json.outputs.json_payload).repo_url }}
          release_tag: ${{ fromJson(needs.parse-json.outputs.json_payload).release_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: 'INFO'
          
      - name: Capture log output
        id: capture-logs
        if: always()
        run: |
          # The logs should be available in the action's output
          # Create a file to store them if not already captured
          if [ -f "result.txt" ]; then
            cat result.txt
          else
            echo "No log file found, attempting to use step outputs"
            # Try to get logs from the previous step's outputs if available
            echo "${{ steps.add-release.outputs.result }}" > result.txt
          fi
          
          # Set up the log output for GitHub Actions
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          RESULT=$(cat result.txt)
          echo "result<<$EOF" >> $GITHUB_OUTPUT
          echo "$RESULT" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          
          # Determine if the step failed
          if [ "${{ steps.add-release.outcome }}" != "success" ]; then
            echo "failed=true" >> $GITHUB_OUTPUT
          else
            echo "failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Post failure Results 
        uses: peter-evans/create-or-update-comment@v3
        if: steps.add-release.outcome != 'success'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Failed to add release to package DB. Please check the logs below for more details.
            After addressing the errors, reply "retry"

            ```
            ${{ steps.capture-logs.outputs.result }}
            ```
            
            Check out the [Unchained Discord](https://discord.gg/chiv2unchained) for support.

      - name: Commit changes
        if: steps.add-release.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add release via issue #${{ github.event.issue.number }}"
          branch: db
          file_pattern: package_db
      
      - name: Post success results
        uses: peter-evans/create-or-update-comment@v3
        if: steps.add-release.outcome == 'success'
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Successfully added release to package DB.
            ```
            ${{ steps.capture-logs.outputs.result }}
            ```

      - name: Close Issue
        if: steps.add-release.outcome == 'success'
        run: gh issue close "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
