name: Run tests

on:  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:  
  check-should-execute:
    runs-on: ubuntu-latest
    # If the ref is main, this is an issue comment so do nothing. Otherwise its a PR
    # If the event_name is pull_request, this is a PR event, so its valid
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if this should execute
        id: check
        run: |
          shopt -s nocasematch
          SHOULD_EXECUTE=true

          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" != "retry" ]]; then
              SHOULD_EXECUTE=false
            fi
          fi

          echo "should_execute=$SHOULD_EXECUTE" >> $GITHUB_OUTPUT

  update-package-list-dry-run:
    # Necessary to be able to merge the PR
    permissions: write-all

    runs-on: ubuntu-latest
    needs: check-should-execute 
    if: needs.check-should-execute.outputs.should_execute == 'true'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge db branch -> PR branch
        run: |
          git fetch origin db 
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git merge origin/db

      - name: Attempt to initialize updated package list
        id: update-package-list
        uses: Chiv2-Community/zero-infra-mod-registry@main
        with:
          command: process-registry-updates
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: INFO

      - name: Post failure Results 
        uses: peter-evans/create-or-update-comment@v3
        if: steps.update-package-list.outputs.failed == 'true'
        with:
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Failed to add release to package DB. Please check the logs below for more details.
            After addressing the errors, reply "retry"
            
            ```
            ${{ steps.update-package-list.outputs.result }}
            ```

            Check out the [Unchained Discord](https://discord.gg/chiv2unchained) for support.

      - name: Post success results
        uses: peter-evans/create-or-update-comment@v3
        if: steps.update-package-list.outputs.failed == 'false'
        with:
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Successfully processed new packages. Contact an admin in the [Unchained Discord](https://discord.gg/chiv2unchained) for approval.

            ```
            ${{ steps.update-package-list.outputs.result }}
            ```
