name: Run tests

on:  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:  
  add-pr-to-project:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: Add PR to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Chiv2-Community/projects/4
          github-token: ${{ secrets.PROJECT_MANAGER_PAT }}
          
  check-should-execute:
    runs-on: ubuntu-latest
    # If the ref is main, this is an issue comment so do nothing. Otherwise its a PR
    # If the event_name is pull_request, this is a PR event, so its valid
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if this should execute
        id: check
        run: |
          shopt -s nocasematch
          SHOULD_EXECUTE=true

          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" != "retry" ]]; then
              SHOULD_EXECUTE=false
            fi
          fi

          echo "should_execute=$SHOULD_EXECUTE" >> $GITHUB_OUTPUT

  update-package-list-dry-run:
    # Necessary to be able to merge the PR
    permissions: write-all

    runs-on: ubuntu-latest
    needs: check-should-execute 
    if: needs.check-should-execute.outputs.should_execute == 'true'
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Merge db branch -> PR branch
        run: |
          git fetch origin db 
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git merge origin/db

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Setup a local virtual environment 
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Attempt to initialize updated package list
        id: update-package-list
        run: .github/workflows/scripts/run-package-manager.sh --dry-run process-registry-updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post failure Results 
        uses: peter-evans/create-or-update-comment@v3
        if: steps.update-package-list.outputs.failed == 'true'
        with:
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Failed to add release to package DB. Please check the logs below for more details.
            After addressing the errors, reply "retry"

            ```
            ${{ steps.update-package-list.outputs.result }}
            ```

      - name: Commit changes
        if: steps.update-package-list.outputs.failed == 'false'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package list
          branch: db
          file_pattern: package_db
      
      - name: Post success results
        uses: peter-evans/create-or-update-comment@v3
        if: steps.update-package-list.outputs.failed == 'false'
        with:
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: Successfully added release to package DB.

      - name: Merge PR
        if: steps.update-package-list.outputs.failed == 'false'
        run: gh pr merge ${{ github.event.issue.number || github.event.pull_request.number }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
