name: Run tests

on:  
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:  
  check-should-execute:
    runs-on: ubuntu-latest
    # If the ref is main, this is an issue comment so do nothing. Otherwise its a PR
    # If the event_name is pull_request, this is a PR event, so its valid
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    outputs:
      should_execute: ${{ steps.check.outputs.should_execute }}
    steps:
      - name: Check if this should execute
        id: check
        run: |
          shopt -s nocasematch
          SHOULD_EXECUTE=true

          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" != "retry" ]]; then
              SHOULD_EXECUTE=false
            fi
          fi

          echo "should_execute=$SHOULD_EXECUTE" >> $GITHUB_OUTPUT
