name: Update package list
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  merge-branch:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Merge main into db
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: db
          message: Merge main into db
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-package-list:
    runs-on: ubuntu-latest
    needs: merge-branch
    permissions:
      contents: write
    steps:
      - name: Checkout db branch
        uses: actions/checkout@v3
        with: 
          ref: db

      - name: Update package list
        uses: Chiv2-Community/zero-infra-mod-registry@main
        id: update-package-list
        with:
          command: process-registry-updates
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: INFO

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package list
          branch: db
          file_pattern: package_db
