name: Update package list
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  merge-branch:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Merge main into db
        uses: everlytic/branch-merge@1.1.5
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: db
          commit_message_template: Merge main into db
