name: Update package list
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  merge-branch:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@master

      - name: Merge main into db
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: db
          message: Merge main into db
          github_token: ${{ secrets.GITHUB_TOKEN }}

  update-package-list:
    runs-on: ubuntu-latest
    needs: merge-branch
    permissions:
      contents: write  # Needed for making changes to repo
    steps:
      - name: Checkout db branch
        uses: actions/checkout@v3
        with: 
          ref: db

      - name: Process registry updates
        id: update-package-list
        uses: Chiv2-Community/zero-infra-mod-registry@main
        with:
          command: process-registry-updates
          github_token: ${{ secrets.GITHUB_TOKEN }}
          log_level: 'INFO'
          
      - name: Capture log output
        id: capture-logs
        if: always()
        run: |
          # The logs should be available in the action's output
          # Create a file to store them if not already captured
          if [ -f "result.txt" ]; then
            cat result.txt
          else
            echo "No log file found, attempting to use step outputs"
            # Try to get logs from the previous step's outputs if available
            echo "${{ steps.update-package-list.outputs.result }}" > result.txt
          fi
          
          # Log to GitHub step summary
          if [ "${{ steps.update-package-list.outcome }}" != "success" ]; then
            echo ":x: Failed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat result.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo ":white_check_mark: All checks passed." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat result.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Commit changes
        if: steps.update-package-list.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update package list
          branch: db
          file_pattern: package_db
